### ISSUE TITLE
Document size is too large

### ISSUE THREAD

**Issue by AlbertoJALJ** [telemark/generate-docx#187]
Hey! Is there anyway to decrease the docx size? is using 12mb per document.

**Comment by zrrrzzt** [comment]
This module is just a thin wrapper around [the docxtemplater module](https://github.com/open-xml-templating/docxtemplater#readme) So you might have better luck asking you questions there.

**Comment by AlbertoJALJ** [comment]
> This module is just a thin wrapper around [the docxtemplater module](https://github.com/open-xml-templating/docxtemplater#readme) So you might have better luck asking you questions there.

Ok thanks

**Comment by sebRomeo** [comment]
@AlbertoJALJ I don't see your question on the docx templater issues....Have you managed to get a solution ?
