### ISSUE TITLE
How can we use this in angular 4  ?

### ISSUE THREAD

**Issue by itsSandeepNandey** [telemark/generate-docx#63]
Hi , 
I am new to angular 4 and finding  it difficult to implement this code in Angular 4 .

Can you please share the sample code for same code be implemented in Angular 4!

Thanks

**Comment by bensleveritt** [comment]
I could be way off here, but I think this is a node library. Usage with client-only frameworks won't be possible as it interacts with the filesystem directly.

Isomorphic app usage would be possible, but that's a fair bit more complex, as you'd still have to generate the document on the server, and pass it back to the frontend.
